name: GitHub Actions Demo
run-name: ${{ github.actor }} deployed page
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node
        run: |
          pnpm install
      - name: npm run deploy
        run: |
          npm run deploy
      - run: echo "🍏 This job's status is ${{ job.status }}
